name: Full Test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build TypeScript
        run: npm run build
      
      - name: Run linting
        run: npm run lint
      
      - name: Run tests
        run: npm test
      
      - name: Test CLI functionality
        run: |
          echo '{"name":"Alice","age":30,"active":true}' | node dist/cli.js encode
          echo 'name="Alice"' | node dist/cli.js decode
      
      - name: Test round-trip conversion with examples
        run: |
          if [ -f "examples/modern.roml" ]; then
            cat examples/modern.roml | node dist/cli.js decode | node dist/cli.js encode
          fi

  package-test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Test npm pack
        run: npm pack
      
      - name: Verify package contents
        run: tar -tzf *.tgz | head -20
